# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 19:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('labelgame', '0002_image_img_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='label',
            name='user',
        ),
        migrations.RemoveField(
            model_name='image',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='image',
            name='filepath',
        ),
        migrations.AddField(
            model_name='image',
            name='uploaded_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='totalvotes',
            name='image',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='labelgame.Image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.CharField(default=None, max_length=512, null=True, verbose_name='Description of the image, where and when it was taken'),
        ),
        migrations.AlterField(
            model_name='image',
            name='img_file',
            field=models.FileField(upload_to='images', verbose_name='Select file to upload'),
        ),
        migrations.DeleteModel(
            name='Label',
        ),
    ]
