# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 20:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('labelgame', '0003_auto_20170805_1227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='totalvotes',
            options={'verbose_name_plural': 'total votes'},
        ),
        migrations.AddField(
            model_name='image',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date photo was uploaded.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date photo was changed.'),
        ),
    ]
