# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labelgame', '0007_auto_20170807_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='date_taken',
            field=models.DateField(blank=True, null=True, verbose_name='Date photo was taken.'),
        ),
    ]
