# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 01:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('labelgame', '0008_auto_20170807_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlabel',
            name='image',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='labelgame.Image'),
        ),
        migrations.AddField(
            model_name='userlabel',
            name='sel_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date selected'),
            preserve_default=False,
        ),
    ]
