# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labelgame', '0010_auto_20170822_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlabel',
            name='sel_animal',
            field=models.CharField(choices=[('Wolf', 'Wolf'), ('Bear', 'Bear'), ('Monkey', 'Monkey'), ('Not an Animal', 'NotAnimal'), ('Skipped', 'Skipped')], default=None, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Animals',
        ),
    ]
