# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 02:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labelgame', '0011_auto_20170822_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlabel',
            name='name',
        ),
    ]
