# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20170813_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='popularity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
